# Generated by Django 5.2.17 on 2026-08-17 15:02

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='learningitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='learningitem',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='estimated_hours',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='resource_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='topic',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='learningitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
